### ISSUE TITLE
Failing to build v0.5.14 on Windows

### ISSUE THREAD

**Issue by mindeka** [w1nk/node-odbc#44]
Built v0.4.4 successfully, but it doesn't work with unicode strings in MS SQL,
so now my hope lies with v0.5.14 by @wankdanker 
I would appreciate any pointers.

Here's node-gyp output

```
PS C:\Users\XXX\node-test> npm install git://github.com/wankdanker/node-odbc.git

> odbc@0.5.14 preinstall C:\Users\XXX\node-test\node_modules\odbc
> node-gyp configure build


C:\Users\XXX\node-test\node_modules\odbc>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
..\src\odbc_connection.cpp(198): warning C4267: 'argument' : conversion from 'size_t' to 'SQLSMALLINT', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_connection.cpp(758): warning C4267: 'argument' : conversion from 'size_t' to 'SQLINTEGER', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_connection.cpp(765): warning C4267: 'argument' : conversion from 'size_t' to 'SQLINTEGER', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(363): warning C4244: 'argument' : conversion from 'SQLLEN' to 'double', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(420): warning C4244: 'argument' : conversion from 'SQLLEN' to 'double', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(473): warning C4267: 'argument' : conversion from 'size_t' to 'SQLINTEGER', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(597): warning C4267: 'argument' : conversion from 'size_t' to 'SQLINTEGER', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(664): warning C4267: 'argument' : conversion from 'size_t' to 'SQLINTEGER', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(407): error C2065: 'tm_sec' : undeclared identifier [C:\Users\No\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(407): error C2143: syntax error : missing '}' before ':' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(407): error C2143: syntax error : missing ';' before ':' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(407): error C2143: syntax error : missing ';' before ':' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(437): error C2065: 'timeInfo' : undeclared identifier [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(442): error C2065: 'timeInfo' : undeclared identifier [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(442): error C2228: left of '.tm_isdst' must have class/struct/union [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(444): error C2065: 'timeInfo' : undeclared identifier [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(483): error C2043: illegal break [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(484): error C2046: illegal case [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(506): error C2047: illegal default [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(527): error C2059: syntax error : '}' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(527): error C2143: syntax error : missing ';' before '}' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(527): error C2059: syntax error : '}' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(535): error C2143: syntax error : missing ';' before '{' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(535): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(748): warning C4244: 'argument' : conversion from 'SQLINTEGER' to 'SQLSMALLINT', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
Project : warning PRJ0018: The following environment variables were not found:
[C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\XXX\node-test\node_modules\odbc
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by wankdanker** [comment]
Hmmm. Looks like issues with the handling of timestamp/datetime values. I'll see if I can get to a Windows box and look at that section.

**Comment by wankdanker** [comment]
I think I fixed it. v0.5.15 is on my github master, so, try it again please. Let me know how things go; all-around. You are the first to report attempting to use v0.5.x on Windows, so I'm curious about how things go.

Thanks,

Dan

**Comment by mindeka** [comment]
Wow, that was quick. Yes, now it builds succesfully. Much appreciated.

Sadly it doesn't seem to solve the old unicode problem (issue #27) on my query results from SQL Server 2000.
Oh well, it was worth a shot. 
Thanks again.

**Comment by wankdanker** [comment]
Did you try setting `charset=utf8` in the connection string?

**Comment by mindeka** [comment]
FWIW my initial connection string was
`DRIVER={SQL Server};SERVER=XXX-TEST\\SQL2000;UID=sa;PWD=;DATABASE=Northwind;`

I did try adding "charset=utf8", and other things I had googled, such as "CharacterSet=UTF-8", but I still get question marks instead of non-ascii symbols returned from nvarchar fields.

**Comment by wankdanker** [comment]
I have a MSSQL 2005 server and have the '?' issue when using node-odbc from Windows just as you describe. However, it does work when I use node-odbc from Linux to query the same MSSQL server using unixodbc and the freetds driver.

**Comment by wankdanker** [comment]
Hey, I just pushed v0.5.16 to my master branch. It includes a special case for handling these strings in Windows. My tests now work. Nothing special in the connection string is required either. 

Give it a shot and let me know. This will probably also close #27.

**Comment by wankdanker** [comment]
Oh, as an aside, I haven't been able to get the Unicode characters to display properly in the console. Even `console.log('ᗖ');` displays a square or question mark. So, I was doing my tests to an HTTP server and hitting it with FireFox.

**Comment by mindeka** [comment]
You rock :) Yeah, reading seems to be correct now, which is awesome. Writing unicode chars to db still produces garbage for me though.

**Comment by wankdanker** [comment]
:) Glad that works. Thank you for testing the inserting too. Are you using binding parameters? Or just an insert statement?

**Comment by mindeka** [comment]
Both plain insert statement, and also tried with binding params to exec a stored procedure which does update/set, same incorrect result.

**Comment by wankdanker** [comment]
OK. This is going to be a bit more of a pain. Basically anywhere we get a value from Javascript-land, we are converting it to a v8::String::Utf8Value and it would seem that we need to change that to v8::String::Value. And all of the buffers that were just `char *` are now `uint16_t *`. Here we go... :)

**Comment by mindeka** [comment]
Best of luck, I really hope this gets fixed :) Kind of a show stopper to the otherwise awesome plugin.

**Comment by wankdanker** [comment]
Try `npm install git://github.com/wankdanker/node-odbc.git#unicode-madness`. I'm currently testing against sqlite3 and mysql (don't have access to mssql at home) and it seems like a bound parameter that is unicode may work. But  the sql statement itself may not contain unicode characters otherwise it will fail...

If you can tell me that the bound parameters are working for inserts, I might be on the right path.

**Comment by mindeka** [comment]
I'm clueless when it comes to fixing compile errors, now I fail to compile that with 

```
PS C:\Users\XXX\node-test> npm install git://github.com/wankdanker/node-odbc.git#unicode-madness
npm WARN package.json restler@2.0.1 No repository field.

> odbc@0.5.16 preinstall C:\Users\XXX\node-test\node_modules\odbc
> node-gyp configure build

C:\Users\XXX\node-test\node_modules\odbc>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
..\src\odbc_connection.cpp(198): warning C4267: 'argument' : conversion from 'size_t' to 'SQLSMALLINT', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(363): warning C4244: 'argument' : conversion from 'SQLLEN' to 'double', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(527): warning C4244: 'argument' : conversion from 'SQLLEN' to 'int', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(420): warning C4244: 'argument' : conversion from 'SQLLEN' to 'double', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(473): warning C4267: 'argument' : conversion from 'size_t' to 'SQLINTEGER', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(597): warning C4267: 'argument' : conversion from 'size_t' to 'SQLINTEGER', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc.cpp(751): warning C4244: 'argument' : conversion from 'SQLINTEGER' to 'SQLSMALLINT', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_statement.cpp(664): warning C4267: 'argument' : conversion from 'size_t' to 'SQLINTEGER', possible loss of data [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_connection.cpp(762): error C2664: 'SQLExecDirectW' : cannot convert parameter 2 from 'uint16_t *' to 'SQLWCHAR *' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
..\src\odbc_connection.cpp(769): error C2664: 'SQLPrepareW' : cannot convert parameter 2 from 'uint16_t *' to 'SQLWCHAR *' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(218): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
C:\Users\XXX\.node-gyp\0.10.12\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
Project : warning PRJ0018: The following environment variables were not found: [C:\Users\XXX\node-test\node_modules\odbc\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\XXX\node-test\node_modules\odbc
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by wankdanker** [comment]
I think I got that compile error fixed if you want to try again. Thanks.

**Comment by mindeka** [comment]
Well, plain insert statements with unicode chars don't fail per se, but insert "?" instead of those chars that are not on the system/db(?) codepage even for nvarchar type (I guess for varchar this actually is expected behavior?). 

Inserting unicode via binding parameters, actually seems to work properly now. Yay!

**Comment by wankdanker** [comment]
Well, the stored procedures thing seems to be something nice. :)

Looks like you are doing it right, or at least as I would do it. I'm curious what happens if your bound values are strictly Unicode characters.

``` javascript
db.query("insert into a (avarchar, anvarchar) values (?, ?)", ["ąčęėįšųūžáäàéêèóöòüßÄÖÜ€ шчябы", "ąčęėįšųūžáäàéêèóöòüßÄÖÜ€ шчябы"], function (error, result) {
    if (error) {
        console.log(error); 
        return false;
    }

    console.log(result);
});
```

Not that I would really know what to make of the outcome of that test. :)

**Comment by mindeka** [comment]
Sorry, that error was due to a dumb mistake on my part, didn't notice that one of the target varchar fields wasn't big enough to fit the passed string.
Inserting unicode via binding parameters actually seems to work correctly now whether it's being passed to stored proc or not.

**Comment by wankdanker** [comment]
Well, that's good news. Not sure why it's not working out in the sql string itself. Character sets and code pages drive me to drink. :beer:

**Comment by wankdanker** [comment]
OK, here is where we stand as of the latest pushes to the `unicode-madness` branch. 

On Linux, I can transmit Unicode values in both bound parameters and in the sql string to sqlite3 and mysql. When testing against MSSQL, they get replaced by '?'. 

On Windows, I can properly transmit Unicode values by bound parameters. When used in the sql string, I see the actual Unicode character in SQL Profiler. But the value returned is a '?'. 

In Query Manager, I tried executing this:

``` sql
select 'Ⅲ' as test
```

And it returns a '?'. So, I think there may be something up with how my database is configured.

**Comment by mindeka** [comment]
Beats me. All that crap is probably the worst invention of the last century. It's too bad around here we still have quite a lot of legacy software using these outdated localization methods. 
Anyway, since binding params seem to work now, I don't wanna bug you any further. Too much :beers: is bad for health :) If it gets fixed in sql trings at some point - awesome, if not - oh well. 
Can't thank you enough for your responsiveness and fixes, man!

**Comment by wankdanker** [comment]
Sure thing, man. I'm glad that the binding params is good enough for you. I want this module to be as complete and bug free as possible, so finding all these weird things is helpful. Hopefully, I'll figure out the sql string thing eventually.  Thank you for your help. :)

I'm closing this issue and will open a new one for just the Unicode SQL string issue.
