### ISSUE TITLE
dynodbc and 1.1.0

### ISSUE THREAD

**Issue by amcintyre99** [w1nk/node-odbc#84]
install gets an error
https://gist.github.com/amcintyre99/23198c6347e2347fb853

but bench code works anyway, yea!!
$ node -v
v0.12.2
$ node db2-bench-prepare-executeNonQuery.js 
100000 queries issued in 30.798 seconds, 3246/sec : Prepare - ExecuteNonQuery

however, rebuild with dynodbc get this
https://gist.github.com/amcintyre99/c588fb2018675b385841

and thanks!!

**Comment by wankdanker** [comment]
Thanks, @amcintyre99 I'll take a look. 

Out of curiosity, how does that bench compare to v0.10? I noticed a pretty drastic drop in performance in v0.12.2.

**Comment by wankdanker** [comment]
Can you try installing with `npm install wankdanker/node-odbc#v1.0-fix-dynodbc` and see if that works. You'll have to set the dynodbc flag manually.

**Comment by amcintyre99** [comment]
for some reason the npm install command you gave just hangs

$ npm remove odbc
unbuild odbc@1.1.0
$ npm install wankdanker/node-odbc#v1.0-fix-dynodbc

normal install still works like yesterday
$ npm install odbc
\

> odbc@1.1.0 install /home/andrew/node_modules/odbc
> node-gyp rebuild
> ..........

**Comment by wankdanker** [comment]
Hmmmm. Maybe try with `npm install https://github.com/wankdanker/node-odbc/archive/v1.0-fix-dynodbc.tar.gz`.

**Comment by amcintyre99** [comment]
had to switch to a different server (long story)... and that last npm cmd didn't hang...

but install failed with
https://gist.github.com/amcintyre99/c3c639b2627cf561055a

**Comment by amcintyre99** [comment]
went back to your first npm command and it didn't hang...
might have been me not waiting long enough :-)

but still got this
https://gist.github.com/amcintyre99/f929d6bb7e4b64b2e966

**Comment by bzuillsmith** [comment]
That first warning should be fixed with the latest patch posted a few hours ago. That error seems to be specific to your build environment. I can't reproduce it. We'll have to see what else we can do on that line to get it to compile.

**Comment by bzuillsmith** [comment]
ok try this

```npm install git+https://github.com/bzuillsmith/node-odbc.git```

**Comment by amcintyre99** [comment]
installed node 12 with standard nodesource instructions
https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

still no go
https://gist.github.com/amcintyre99/ace85f0a34ed31d33dd2

**Comment by amcintyre99** [comment]
now i'm confused... can't get 1.1.0 working which worked at the top of this thread

which was a different server than i'm on now... but same
ubuntu 14.04.2 lts

actually, first one was ubuntu server and now i'm testing on ubuntu desktop... until sunday when server farm comes back up (maint weekend) and i can report both results

sign, confused

**Comment by amcintyre99** [comment]
ubuntu desktop
https://gist.github.com/amcintyre99/9a15c6c4e0e0ad55190d

**Comment by bzuillsmith** [comment]
Give this fix a try:
`npm install bzuillsmith/node-odbc#dynofix`

**Comment by amcintyre99** [comment]
default install works!! thanks!!
https://gist.github.com/amcintyre99/57b42fed85ec9af54884

dynodbc, not so much
https://gist.github.com/amcintyre99/cdfd05418b3614b17ef1

**Comment by amcintyre99** [comment]
saw your comment in bottom of gist thread...

anyway so just tried this
      'defines' : [
        'UNICODE dynodbc'

and it compiles but bench gets symbol error on SQLAllocHandle
https://gist.github.com/amcintyre99/8cd26d53274a1d27159c

**Comment by amcintyre99** [comment]
if i put the lib spec back
      'defines' : [
        'UNICODE dynodbc'
      ],
      'conditions' : [
        [ 'OS == "linux"', {
          'libraries' : [
            '-lodbc'

i get around the symbol error but from the bench time i'm pretty sure i'm not getting dynodbc

**Comment by bzuillsmith** [comment]
Unfortunately I don't know enough about the dynodbc portion of the code to help you further. @wankdanker might be able to help you. He did mention to me that node v12 (or probably the v8 engine used in node.js, iojs, etc.) seems to have slowed the performance of node-odbc quite a bit.

**Comment by wankdanker** [comment]
Not sure if it makes a difference but I always specify the defines separately:

``` gyp
'defines' : [
'UNICODE', 'dynodbc'
],
```

It compiles for me but I haven't actually run a test with the dynodbc turned on. I'll give it shot at some point today.

**Comment by amcintyre99** [comment]
`npm install bzuillsmith/node-odbc#dynofix` compiles clean
https://gist.github.com/amcintyre99/7837f232e1e9b2e18773

adding dynodbc and deleting lib
      'defines' : [
        'UNICODE', 'dynodbc'
      ],
      'conditions' : [
        [ 'OS == "linux"', {
          'libraries' : [

```
      ],
```

gets this
https://gist.github.com/amcintyre99/c890737380dbc80b4bda

**Comment by bzuillsmith** [comment]
Those are just warnings. They can be ignored.

**Comment by amcintyre99** [comment]
ok, yes it did compile... I missed that, sorry

but the bench output looks a little funny :-)
$ node db2-bench-prepare-executeNonQuery.js 
{ [Error: 䥛䵂孝䱃⁉牄癩牥⁝兓ㅌ㈰临†⁁慤慴慢敳挠湯敮瑣潩⁮潤獥渠瑯攠楸瑳‮匠䱑呓呁㵅㠰〰ਲ਼＀]
  errors: 
   [ { message: '䥛䵂孝䱃⁉牄癩牥⁝兓ㅌ㈰临†⁁慤慴慢敳挠湯敮瑣潩⁮潤獥渠瑯攠楸瑳‮匠䱑呓呁㵅㠰〰ਲ਼＀',
       state: '㠰〰1' } ],
  error: '[node-odbc] SQL_ERROR',
  message: '䥛䵂孝䱃⁉牄癩牥⁝兓ㅌ㈰临†⁁慤慴慢敳挠湯敮瑣潩⁮潤獥渠瑯攠楸瑳‮匠䱑呓呁㵅㠰〰ਲ਼＀',
  state: '㠰〰1' }

**Comment by amcintyre99** [comment]
still using this
`npm install bzuillsmith/node-odbc#dynofix`

back to just dynodbc and now its working... and i'm confused again
$ node db2-bench-prepare-executeNonQuery.js 
100000 queries issued in 10.413 seconds, 9603/sec : Prepare - ExecuteNonQuery 
connection closed

i will try and do some comparisons with 10

**Comment by amcintyre99** [comment]
the bench results for
10 vs 12
6.13 vs 1.1.0
unicode vs dynodbc (can't do both)

aren't consistent enough to draw any conclusions...

at least on ubuntu desktop box... maybe when server gets back online

so will this fix be rolled up to the next release? or whatever the term is :-)
bzuillsmith/node-odbc#dynofix

thanks!!

**Comment by bzuillsmith** [comment]
The odd characters are related to using Unicode with a non unicode system (Unless we coded it wrong).

I pushed an update to fix the compile error that occurred when you did not have UNICODE defined which is why it works now.

**Comment by bzuillsmith** [comment]
And yes, a pull request has been made to the main repo. Just waiting for it's approval. Thanks!

**Comment by wankdanker** [comment]
Just released [v1.1.2 on npm](https://www.npmjs.com/package/odbc). In my testing, I had to have UNICODE disabled with the dynodbc flag on.

**Comment by amcintyre99** [comment]
some numbers
https://gist.github.com/amcintyre99/56c941a47291d5fef293

**Comment by wankdanker** [comment]
Thank you for the benchmarks, @amcintyre99. It looks like nan (node-odbc@1.1.2) with dynodbc on v0.10.38 is equivalent to or better than node-odbc@0.6.13, which is good to see.

The performance on v0.12.2 is similar to what I was seeing too. I haven't done much to see if there is anything we can to optimize on v0.12.2; hopefully there is something that can be done.

**Comment by amcintyre99** [comment]
updated link with iojs 2.0.0 numbers - best dynodbc so far, i think
https://gist.github.com/amcintyre99/56c941a47291d5fef293
